---
title: "Supervision 01"
subtitle: "Michaelmas 2025"
format: pdf
editor: visual
---

## Question 1: Consumption based asset pricing

Consider the consumption based asset pricing model with log utility, where the representative consumer solves
$$
\underset{\{c_t,\ b_{t+1},\ a_{t+1} \}}{\text{max}}_{t=0}^\infty \mathbb{E}\sum_{t=0}^\infty\beta^t\ln c_t
$$
subject to $c_t+b_{t+1}+p_ta_{t+1}=(p_t+d_t)a_t+R_t^fb_t,\ t=1,2,\dots$ and $a_0,b_0$ given, where $c_t$ is consumption, $b_t$ is a risk-free asset that pays a risk free return $R_t^f$, $a_t$ is the risk asset at price $p_t$ and $d_t$ is the stochastic exogenous divident paid to those who hold the risky asset. To close the model, assume that $a_t=1,\ b_t=0$ and $d_t=c_t$, as we saw in the lectures.

(a)   Derive asset pricing equation, i.e.e the Euler equation for the risky asset, in general equilibrium, and show that it can be expressed in terms of the price-divident ratio $q_t\equiv p_t/d_t$.

(b)   Starting from the asset pricing equation in (a) derive the NPV representation of the price-dividend ratio and show that it is constant.

(c)   Interpret your expression from (b) and evaluate the empirical relevance of this equilibrium asset pricing model.